name: Deploy Node.js App to Azure VM

on:
  push:
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_IP_ADDRESS }} >> ~/.ssh/known_hosts

    - name: Upload app to Azure VM
      run: |
        rsync -avz ./app/ ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP_ADDRESS }}:/home/${{ secrets.SSH_USERNAME }}/app

    - name: Install deps and restart app
      run: |
        ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP_ADDRESS }} << 'EOF'
          set -e
          cd ~/app
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
          command -v pm2 >/dev/null || sudo npm install -g pm2
          pm2 delete myapp || true
          pm2 start server.js --name myapp
          pm2 save
        EOF
